apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: dating-app
spec:
  type: ClusterIP
  selector:
    app: dating-app-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
